wandb_version: 1

env_name:
  desc: null
  value: car
policy:
  desc: null
  value: Gaussian
eval:
  desc: null
  value: false
gamma:
  desc: null
  value: 0.999
tau:
  desc: null
  value: 0.005
lr:
  desc: null
  value: 0.00015
alpha:
  desc: null
  value: 0.2
automatic_entropy_tuning:
  desc: null
  value: false
seed:
  desc: null
  value: 123456
batch_size:
  desc: null
  value: 32
num_steps:
  desc: null
  value: 10000
hidden_size:
  desc: null
  value: 64
updates_per_step:
  desc: null
  value: 1
start_steps:
  desc: null
  value: 32
target_update_interval:
  desc: null
  value: 1
replay_size:
  desc: null
  value: 1000000
cuda:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716426833
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.0
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
